### ISSUE TITLE
Explicitly define @support at-rule order

### ISSUE THREAD

**Issue by saneef** [hudochenkov/stylelint-config-hudochenkov#2]
Shouldn't be `@support {}` be defined after the declarations. In order to override, or define new declaration based on the support?

Can we keep it between `at-rule: keyframes` and `at-rule: media`?

**Comment by hudochenkov** [comment]
Sounds good. I would even say replace `keyframes` with `supports`. I don't remember why I even put `keyframes` there, as there is no sense to keep it nested into the rule.

**Comment by saneef** [comment]
I agree, with replacing `keyframes` with `supports`.

**Comment by hudochenkov** [comment]
Released in `5.0.0`.
